## Cleaning and Formatting the Graph Data ##

This data is used to display content on the website, including name and country details, as well as the internet and economic indicators used for visualizations. This notebook also cleans the time series json file used to generate the graphs. The data cleaned includes datasets with actual values and datasets with normalized values which are used for modelling.

In [8]:
# Import libraries

import json
import pandas as pd

#### 1. Read and format json file with actual, unscaled values.

In [9]:
# Load json file with all of the data containing the real, unscaled values
file_path = "real_data.json"
with open(file_path, "r", encoding="utf-8") as file:
    raw_data = json.load(file)

real_df = pd.DataFrame(raw_data)
real_df = real_df.rename(columns={"year": "Year"})

# Filter data from 2015
real_df = real_df[(real_df["Year"] >= 2015) & (real_df["Year"] <= 2023)]
display(real_df)

,Country Name,Year,Economic Index,v4_prefixes_ris,v6_prefixes_ris,asns_ris,v4_prefixes_stats,v6_prefixes_stats,asns_stats,speed (mgps),bandwidth (kbit/s),GDP per Capita,GDP,GNI,GNI per Capita,Foreign Investment,GINI Index,Unemployment Rate,Labor Force participation rate
0,Qatar,2022,0.402156,123555.0,96985.5,4868.0,-348.0,-348.0,6323.0,86.88,255102.7,88701.463350,2.357093e+11,2.274817e+11,71070.0,7.609890e+07,NaN,0.130,87.575
1,Qatar,2023,0.385429,129173.0,118954.0,4515.0,-339.0,-339.0,6658.0,153.89,NaN,80195.874647,2.130028e+11,2.069289e+11,79430.0,-4.741758e+08,NaN,0.130,87.550
2,Luxembourg,2021,0.371657,351576.5,54919.0,27952.0,-351.0,-351.0,40907.0,173.16,NaN,133711.794436,8.558411e+10,5.863045e+10,87610.0,5.217423e+10,32.7,5.571,61.482
3,Qatar,2018,0.367351,105487.0,4389.0,3245.0,-354.0,-354.0,5306.0,32.79,106632.7,71039.849058,1.833350e+11,1.795896e+11,63410.0,-2.186264e+09,NaN,0.110,87.503
4,Qatar,2021,0.364576,115112.0,71760.5,4514.0,-347.0,-347.0,5995.0,109.57,247955.6,71751.883123,1.797320e+11,1.769691e+11,66970.0,-1.093407e+09,NaN,0.140,86.363
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1693,"Yemen, Rep.",2019,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,623.376165,NaN,NaN,NaN,3.331220e+06,NaN,17.202,32.747
1694,"Yemen, Rep.",2020,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,559.564673,NaN,NaN,NaN,NaN,NaN,17.953,32.506
1695,"Yemen, Rep.",2021,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,522.173513,NaN,NaN,NaN,NaN,NaN,18.287,32.405
1696,"Yemen, Rep.",2022,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,615.702079,NaN,NaN,NaN,NaN,NaN,17.363,32.897
1697,"Yemen, Rep.",2023,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,477.409029,NaN,NaN,NaN,NaN,NaN,17.091,32.960

In [10]:
# Sort by 'Country Name' and 'Year'
real_df = real_df.sort_values(
    by=["Country Name", "Year"], ascending=[True, True]
).reset_index(drop=True)

# Drop columns not needed for graphs; most of these values are represented through similar metrics
columns = [
    "v4_prefixes_stats",
    "v6_prefixes_stats",
    "asns_stats",
    "GINI Index",
    "GDP per Capita",
    "GDP",
    "GNI",
    "Economic Index",
]
real_df = real_df.drop(columns, axis=1)
display(real_df)

,Country Name,Year,v4_prefixes_ris,v6_prefixes_ris,asns_ris,speed (mgps),bandwidth (kbit/s),GNI per Capita,Foreign Investment,Unemployment Rate,Labor Force participation rate
0,Albania,2015,127279.0,2148.0,14094.0,NaN,59141.6,4390.0,9.895783e+08,17.193,55.497
1,Albania,2016,150756.0,6256.0,14615.0,NaN,70612.7,4320.0,1.044390e+09,15.418,57.314
2,Albania,2017,175758.5,9822.0,17404.0,11.48,87693.3,4290.0,1.022758e+09,13.616,58.057
3,Albania,2018,205471.5,12964.0,19280.0,14.71,NaN,4880.0,1.204383e+09,12.304,59.296
4,Albania,2019,216759.5,17664.0,20571.0,28.61,NaN,5280.0,1.201022e+09,11.466,60.306
...,...,...,...,...,...,...,...,...,...,...,...
643,"Yemen, Rep.",2019,NaN,NaN,NaN,NaN,NaN,NaN,3.331220e+06,17.202,32.747
644,"Yemen, Rep.",2020,NaN,NaN,NaN,NaN,NaN,NaN,NaN,17.953,32.506
645,"Yemen, Rep.",2021,NaN,NaN,NaN,NaN,NaN,NaN,NaN,18.287,32.405
646,"Yemen, Rep.",2022,NaN,NaN,NaN,NaN,NaN,NaN,NaN,17.363,32.897
647,"Yemen, Rep.",2023,NaN,NaN,NaN,NaN,NaN,NaN,NaN,17.091,32.960

In [11]:
# Map names and apply the mapping to standardize country names
name_map = {
    "Bosnia and Herzegowina": "Bosnia and Herzegovina",
    "Bosnia And Herzegovina": "Bosnia and Herzegovina",
    "Iran, Islamic Rep.": "Iran",
    "Kyrgyz Republic": "Kyrgyzstan",
    "Slovak Republic": "Slovakia",
    "West Bank and Gaza": "Palestine",
    "Åland Islands": "Aland Islands",
    "Vatican City State": "Holy See",
    "Türkiye": "Turkey",
    "Turkiye": "Turkey",
    "Yemen, Rep.": "Yemen",
}

real_df["Country Name"] = real_df["Country Name"].str.strip()
real_df["Country Name"] = real_df["Country Name"].replace(name_map)
display(real_df)

,Country Name,Year,v4_prefixes_ris,v6_prefixes_ris,asns_ris,speed (mgps),bandwidth (kbit/s),GNI per Capita,Foreign Investment,Unemployment Rate,Labor Force participation rate
0,Albania,2015,127279.0,2148.0,14094.0,NaN,59141.6,4390.0,9.895783e+08,17.193,55.497
1,Albania,2016,150756.0,6256.0,14615.0,NaN,70612.7,4320.0,1.044390e+09,15.418,57.314
2,Albania,2017,175758.5,9822.0,17404.0,11.48,87693.3,4290.0,1.022758e+09,13.616,58.057
3,Albania,2018,205471.5,12964.0,19280.0,14.71,NaN,4880.0,1.204383e+09,12.304,59.296
4,Albania,2019,216759.5,17664.0,20571.0,28.61,NaN,5280.0,1.201022e+09,11.466,60.306
...,...,...,...,...,...,...,...,...,...,...,...
643,Yemen,2019,NaN,NaN,NaN,NaN,NaN,NaN,3.331220e+06,17.202,32.747
644,Yemen,2020,NaN,NaN,NaN,NaN,NaN,NaN,NaN,17.953,32.506
645,Yemen,2021,NaN,NaN,NaN,NaN,NaN,NaN,NaN,18.287,32.405
646,Yemen,2022,NaN,NaN,NaN,NaN,NaN,NaN,NaN,17.363,32.897
647,Yemen,2023,NaN,NaN,NaN,NaN,NaN,NaN,NaN,17.091,32.960

#### 2. Add internet penetration rate data

In [12]:
from pathlib import Path

# Get path of internet penetration rate csv
BASE_DIR = Path.cwd()
PARENT_DIR = BASE_DIR.parent
file_path = BASE_DIR / "internet_penetration_rate.csv"

ipr_df = pd.read_csv(
    file_path,
    skiprows=4,  # Skip non-data rows
    header=0,
)
# Map names and apply the mapping to standardize country names
ipr_df["Country Name"] = ipr_df["Country Name"].replace(name_map)
display(ipr_df.head())

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2015,2016,2017,2018,2019,2020,2021,2022,2023,Unnamed: 68
0,Aruba,ABW,Individuals using the Internet (% of population),IT.NET.USER.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,88.70,93.5,97.2,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Africa Eastern and Southern,AFE,Individuals using the Internet (% of population),IT.NET.USER.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Afghanistan,AFG,Individuals using the Internet (% of population),IT.NET.USER.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,8.26,11.0,13.5,16.8,17.6,17.0,16.5,17.2,17.7,NaN
3,Africa Western and Central,AFW,Individuals using the Internet (% of population),IT.NET.USER.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Angola,AGO,Individuals using the Internet (% of population),IT.NET.USER.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,22.00,23.2,26.0,29.0,32.1,36.6,39.4,42.1,44.8,NaN

In [13]:
ipr_df = pd.melt(
    ipr_df,
    id_vars=["Country Name"],
    var_name="Year",
    value_name="Internet Penetration Rate",
)

# Convert 'Year' column to numeric values for sorting
ipr_df["Year"] = pd.to_numeric(ipr_df["Year"], errors="coerce")

# Merge dataframes
merged_df = pd.merge(real_df, ipr_df, on=["Country Name", "Year"], how="left")

display(merged_df.head())

,Country Name,Year,v4_prefixes_ris,v6_prefixes_ris,asns_ris,speed (mgps),bandwidth (kbit/s),GNI per Capita,Foreign Investment,Unemployment Rate,Labor Force participation rate,Internet Penetration Rate
0,Albania,2015,127279.0,2148.0,14094.0,NaN,59141.6,4390.0,9.895783e+08,17.193,55.497,56.9
1,Albania,2016,150756.0,6256.0,14615.0,NaN,70612.7,4320.0,1.044390e+09,15.418,57.314,59.6
2,Albania,2017,175758.5,9822.0,17404.0,11.48,87693.3,4290.0,1.022758e+09,13.616,58.057,62.4
3,Albania,2018,205471.5,12964.0,19280.0,14.71,NaN,4880.0,1.204383e+09,12.304,59.296,65.4
4,Albania,2019,216759.5,17664.0,20571.0,28.61,NaN,5280.0,1.201022e+09,11.466,60.306,68.6

#### 3. Save in website directory

In [14]:
# Move up two levels to get parent directory
PARENT_DIR = BASE_DIR.parent.parent

# Write path of json file and save to add it in the web development folder where it is extracted for visualizations
file_path = PARENT_DIR / "web-dev" / "app" / "data" / "graph_data.json"
merged_df.to_json(file_path, orient="records", indent=2)